language: minimal
services:
- docker
addons:
  apt:
    sources:
    - heroku
deploy:
  provider: script
  script: heroku container:push web
  on:
    branch: heroku
env:
  global:
  - secure: DeOXA2m7mq6Y85PBR9cPb3CbrkIzwluDfF5MJ2uy7s9Kn6IA+y2nwb8YyI3JesZkeQmfw7CzeTrTR7WZWBhcGP9b1myQEgbK+p34ZVgwamJUjXQ/h9EXX9VBC8xhL8hYg7z9qMFdvxf6sh6S61j8t0fz56z5XY0AW8ZhoXJUucg=
  - secure: dW5UHnk5q2HOBC4D5HG2C55vB/KzFGs2BHCqIEuRyK3KLkI67jl+CnQztzMsFP6df3h3R3sOJrLGoa5kQVmADFQPO/ggCSdy2pbUwayk7leGTDU7/GQySgH5adwydDcG7oMzv8gPpK4RgOwuwPxPiKmS3Udmn58yHPIukI28i3U=
