version: "3.8"

services:
  web:
    image: bionikspoon/interview-challenge
    restart: always
    volumes:
      - ./sockets:/sockets
    environment:
      GUNICORN_CMD_ARGS: '--workers=4 --bind=unix:/sockets/proxy.sock'